.TH emu3bm 1 "May 2017"

.SH NAME
emu3bm \- manage EMU3 banks

.SH SYNOPSIS
\fBemu3bm\fP [OPTIONS] \fIbank\fP

.SH DESCRIPTION
Manage EMU3 banks, add and extract samples, create presets and set some preset and zone parameters.

.SH OPTIONS
.TP
.BR \-s " sample"
Add the sample to the bank, set the loop points as in the file and set the loop enabled as in the file. If the sample has no loop information ("smpl" chunk is missing), the loop points are set to 0 and the last frame and the loop enabled is set to "off".

.TP
.BR \-S " sample"
Add the sample in WAV format, set the loop points to 0 and the last frame and set loop enabled to "on".

.TP
.BR \-p " preset_name"
Add a new preset with the given name.

.TP
.BR \-z " zone_parameters"
Add a new zone to a preset using the format sample,[pri|sec],original_key,lower_key,higher_key where keys are note names from A-1 to C7. This must be used with \fB\-e\fR.

.TP
.BR \-Z " zone_parameters"
This option is similar to \fB\-z\fR but uses note numbers from 0 to 87.

.TP
.BR \-e " preset_to_edit"
Specify the preset to edit. If no preset is specified all presets will be edited.

.TP
.BR \-c " filter_cutoff_frequency"
Set the cutoff frequency of the VCF for all the preset zones.

.TP
.BR \-f " filter_type"
Set the filter type of the VCF for all the preset zones.

.TP
.BR \-l " level"
Set the level of the VCA for all the preset zones.

.TP
.BR \-n
Create a new bank. Use it with -d to set the device.

.TP
.BR \-d
Set the device type. Only 'esi2000' and 'emu3x' values are allowed. If not used, 'esi2000' is used as the device type.

.TP
.BR \-b " pitch_bend_range"
Set the pitch bend range.

.TP
.BR \-q " filter_q"
Set the Q of the VCF for all the preset zones.

.TP
.BR \-r " realtime_controls"
Set the 8 realtime controls sources separating them by commas.

.TP
.BR \-v
Increment the verbosity level.

.TP
.BR \-x
Extract all the bank samples in the current directory. Exporting samples always includes the loop points and the loop enabled ("on", "off") as stored in the bank.

.TP
.BR \-X
Same as \-x but prepending the sample number to the sample name.

.RE
Options \fB\-s\fR, \fB\-S\fR, \fB\-p\fR, \fB\-z\fR and \fB\-n\fR can not be used in conjuction with options \fB\-c\fR, \fB\-f\fR, \fB\-l\fR, \fB\-b\fR, \fB\-q\fR, \fB\-r\fR and \fB\-x\fR.

.SH COPYRIGHT
Copyright © 2018 David García Goñi. License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
.br
This is free software: you are free to change and redistribute it.  There is NO WARRANTY, to the extent permitted by law.

.SH AUTHOR
Written by David García Goñi.

.SH SEE ALSO
Source code at: <https://github.com/dagargo/emu3bm>
.br
There is a Linux kernel filesystem module at: <https://github.com/dagargo/emu3fs>
