.TH emu3bm 1 "May 2017"

.SH NAME
emu3bm \- manage EMU3 banks

.SH SYNOPSIS
\fBemu3bm\fP [OPTIONS] \fIbank\fP

.SH DESCRIPTION
Manage EMU3 banks, add and extract samples, create presets and set some preset and zone parameters.

.SH OPTIONS
.TP
.BR \-s " sample"
Add the sample in WAV format to the bank without loop enabled.

.TP
.BR \-S " sample"
Add the sample in WAV format to the bank with loop enabled.

.TP
.BR \-p " preset_name"
Add a new preset with the given name.

.TP
.BR \-z " zone_parameters"
Add a new zone to a preset using the format sample,[pri|sec],original_key,lower_key,higher_key,preset.

.TP
.BR \-e " preset_to_edit"
Specify the preset to edit. If no preset is specified all presets will be edited.

.TP
.BR \-c " filter_cutoff_frequency"
Set the cutoff frequency of the VCF for all the preset zones.

.TP
.BR \-f " filter_type"
Set the filter type of the VCF for all the preset zones.

.TP
.BR \-l " level"
Set the level of the VCA for all the preset zones.

.TP
.BR \-n
Create a new EMU SI-32 v3 bank.

.TP
.BR \-b " pitch_bend_range"
Set the pitch bend range.

.TP
.BR \-q " filter_q"
Set the Q of the VCF for all the preset zones.

.TP
.BR \-r " realtime_controls"
Set the 8 realtime controls sources separating them by commas.

.TP
.BR \-v
Increment the verbosity level.

.TP
.BR \-x
Extract all the bank samples in the current directory.

.TP
.BR \-X
Extract all the bank samples in the current directory prepending the sample number to the sample name.

.RE
Options \fB\-s\fR, \fB\-S\fR, \fB\-p\fR, \fB\-z\fR and \fB\-n\fR can not be used in conjuction with options \fB\-c\fR, \fB\-f\fR, \fB\-l\fR, \fB\-b\fR, \fB\-q\fR, \fB\-r\fR and \fB\-x\fR.

.SH COPYRIGHT
Copyright © 2018 David García Goñi. License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
.br
This is free software: you are free to change and redistribute it.  There is NO WARRANTY, to the extent permitted by law.

.SH AUTHOR
Written by David García Goñi.

.SH SEE ALSO
Source code at: <https://github.com/dagargo/emu3bm>
.br
There is a Linux kernel filesystem module at: <https://github.com/dagargo/emu3fs>
