.TH emu4bm 1 "July 2025"

.SH NAME
emu4bm \- manage EMU3 banks

.SH SYNOPSIS
\fBemu4bm\fP [OPTIONS] \fIbank\fP

.SH DESCRIPTION
Manage EIV banks, add and extract samples, create presets and set some preset and zone parameters.

.SH OPTIONS
.TP
.BR \-n
Create a new bank.

.TP
.BR \-s " sample"
Add the sample to the bank, set the loop points as in the file and set the loop enabled as in the file. If the sample has no loop information ("smpl" chunk is missing), the loop points are set to lowest and highest allowed values and the loop enabled is set to "off".

.TP
.BR \-v
Increment the verbosity level.

.TP
.BR \-x
Extract all the bank samples in the current directory. Exporting samples always includes the loop points and the loop enabled ("on", "off") as stored in the bank.

.TP
.BR \-X
Same as \-x but prepending the sample number to the sample name.

.RE
Options \fB\-n\fR, \fB\-s\fR and \fB\-S\fR can not be used in conjuction with options \fB\-x\fR and \fB\-X\fR.

.SH COPYRIGHT
Copyright © 2025 David García Goñi. License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
.br
This is free software: you are free to change and redistribute it.  There is NO WARRANTY, to the extent permitted by law.

.SH AUTHOR
Written by David García Goñi.

.SH SEE ALSO
Source code at: <https://github.com/dagargo/emu4bm>
.br
There is a Linux kernel filesystem module at: <https://github.com/dagargo/emu3fs>
